apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules: 
   - http:
      paths:
      - path: /feed/*
        pathType: Prefix
        backend:
          service:
            name: feed-service
            port:
              number: 8080
